-- Insert into weather
INSERT INTO public.weather (weather_code, weather_description)
VALUES
    (0, 'Clear sky'),
    (1, 'Mainly clear'),
    (2, 'Partly cloudy'),
    (3, 'Overcast'),
    (45, 'Fog'),
    (48, 'Depositing rime fog'),
    (51, 'Light drizzle'),
    (53, 'Moderate drizzle'),
    (55, 'Dense drizzle'),
    (56, 'Light freezing drizzle'),
    (57, 'Dense freezing drizzle'),
    (61, 'Slight rain'),
    (63, 'Moderate rain'),
    (65, 'Heavy rain'),
    (66, 'Light freezing rain'),
    (67, 'Heavy freezing rain'),
    (71, 'Slight snow fall'),
    (73, 'Moderate snow fall'),
    (75, 'Heavy snow fall'),
    (77, 'Snow grains'),
    (80, 'Slight rain showers'),
    (81, 'Moderate rain showers'),
    (82, 'Violent rain showers'),
    (85, 'Slight snow showers'),
    (86, 'Heavy snow showers'),
    (95, 'Slight or moderate thunderstorm'),
    (96, 'Thunderstorm with slight hail'),
    (99, 'Thunderstorm with heavy hail');

-- Insert into genre
INSERT INTO public.genre (weather_id, genre_name, genre_message, genre_upvotes)
VALUES
    (1, 'Pop', 'Suns out! Time for some pop to brighten your day even more.', 0),
    (1, 'Salsa', 'Bright sun and Salsa, the best way to start a festive day.', 0),
    (1, 'Reggae', 'Clear skies and Reggae music are a perfect combo for a chill day.', 0),
    (1, 'Country', 'Country music is a perfect match for a clear, sunny day.', 0),
    (1, 'Funk', 'Clear sky calls for some Funk!', 0),
    (2, 'Indie Rock', 'Mainly clear skies call for Indie Rock!', 0),
    (2, 'Indie Folk', 'Mainly clear skies with Indie Folk, a perfect match!', 0),
    (2, 'New Age', 'New Age music perfectly complements a day with mainly clear skies.', 0),
    (2, 'Dance Pop', 'A Dance Pop kind of day under mainly clear skies.', 0),
    (2, 'Hip Hop', 'Hip Hop under the mainly clear skies.', 0),
    (3, 'Alternative Rock', 'Partly cloudy, perfect for some Alternative Rock!', 0),
    (3, 'Easy Listening', 'Partly cloudy, perfect for Easy Listening!', 0),
    (3, 'Classical', 'Partly cloudy weather goes well with Classical music.', 0),
    (3, 'Ambient', 'Enjoy some Ambient music under partly cloudy skies.', 0),
    (3, 'Post-Punk', 'Enjoy some Post-Punk under the partly cloudy skies.', 0),
    (4, 'Ambient', 'Overcast weather matches well with some Ambient music.', 0),
    (4, 'Gothic Rock', 'Overcast weather matches well with some Gothic Rock music.', 0),
    (4, 'Jazz Fusion', 'Perfect day for some Jazz Fusion with overcast weather.', 0),
    (4, 'Doom Metal', 'Overcast skies? Doom Metal is here for you.', 0),
    (4, 'Electronica', 'Overcast weather? Try Electronica.', 0),
    (5, 'Classical', 'Foggy day? Time for some introspective Classical music.', 0),
    (6, 'Acoustic', 'Depositing rime fog? Perfect for some Acoustic tunes.', 0),
    (7, 'R&B', 'Light drizzle? Try some R&B.', 0),
    (8, 'Country', 'Moderate drizzle goes well with Country music.', 0),
    (9, 'Blues', 'Dense drizzle? Listen to some Blues.', 0),
    (10, 'Folk', 'Freezing drizzle calls for some Folk music.', 0),
    (11, 'Soul', 'Dense freezing drizzle? Try some Soul.', 0),
    (12, 'Blues', 'Slight rain? Try some Blues.', 0),
    (13, 'Reggae', 'Moderate rain? Its Reggae time!', 0),
    (14, 'Rock', 'Heavy rain? Nothing better than some Rock.', 0),
    (15, 'Electronica', 'Light freezing rain? Electronica music is a good match.', 0),
    (16, 'Post-Rock', 'Heavy freezing rain? Listen to some Post-Rock.', 0),
    (17, 'Singer/Songwriter', 'Slight snow fall? Enjoy with Singer/Songwriter music.', 0),
    (18, 'Hard Rock', 'Moderate snow fall? Hard Rock is a great fit.', 0),
    (19, 'Metal', 'Heavy snow fall? Time for some Metal.', 0),
    (20, 'Instrumental', 'Snow grains falling? Instrumental music is a perfect match.', 0),
    (21, 'Dance Pop', 'Slight rain showers? Dance Pop can lift your spirits.', 0),
    (22, 'EDM', 'Moderate rain showers? Pump it up with some EDM!', 0),
    (23, 'Psychedelic Rock', 'Violent rain showers? Psychedelic Rock has got you covered.', 0),
    (24, 'Chillhop', 'Slight snow showers? Chillhop is a perfect companion.', 0),
    (25, 'Lo-fi', 'Heavy snow showers? Lo-fi music is here for you.', 0),
    (26, 'Heavy Metal', 'Thunderstorm? Heavy Metal is the perfect match.', 0),
    (27, 'Progressive Metal', 'Thunderstorm with slight hail? Time for some Progressive Metal.', 0),
    (28, 'Black Metal', 'Thunderstorm with heavy hail - Perfect weather for Black Metal.', 0);

